/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("reportObjectPageObjectPage journey");

        opaTest("Navigate to reportObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThereportList.onFilterBar().iExecuteSearch();

            Then.onThereportList.onTable().iCheckRows();
            When.onThereportList.onTable().iPressRow(0);

            Then.onThereportObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThereportObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Country" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CompanyCode" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CutoffDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Customer" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Rating" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Corporation" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Code" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreditLimit" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "LastPaymentDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CustCreatDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Address" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Phone" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Mobile" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Status" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "BalanceCurrent" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "D0to30" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "D31to60" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "D61to90" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "D91to120" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "D121to150" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Mas151" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TotalBalance" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Currency" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "IdentificationType" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "IdentificationNumber" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AccountNumber" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FullName" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PersonType" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OpenDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "DueDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Situation" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AccountStatus" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "StatusDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "AgingDays" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "InitialAmount" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OutstandingBalance" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MonthlyInstallment" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OverdueBalance" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaidInstallments" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "OverdueInstallments" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaymentDeadline" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaymentDate" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaymentForm" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PaymentFrequency" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FilingOffice" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FilingCity" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "FilingCityCode" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ResidenceCity" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ResidenceCityCode" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ResidenceDept" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ResidenceAddress" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "ResidencePhone" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "WorkCity" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "WorkCityCode" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "WorkDept" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "WorkAddress" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "WorkPhone" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MailCity" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MailCityCode" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MailDept" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "MailAddress" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Email" });
            Then.onThereportObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "TargetSubscriber" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});